{{- if .Values.web.enabled }}
{{ include "kartova.spa.deployment" (dict "root" . "component" "web" "values" .Values.web) }}
---
{{ include "kartova.spa.service" (dict "root" . "component" "web") }}
{{- end }}
