#!/usr/bin/env bash
# qa-discover-files.sh — Discovers and classifies source files for quality analysis.
#
# Usage:
#   bash .claude/scripts/qa-discover-files.sh [--mode main|feature] [--scope <glob>] [--base-branch <branch>]
#
# Outputs (to /tmp/qa_*):
#   /tmp/qa_all_source.txt        — all source files after exclusions (path per line)
#   /tmp/qa_excluded_generated.txt — files excluded as generated code (reason|path)
#   /tmp/qa_excluded_dto.txt       — files classified as pure DTO (path per line)
#   /tmp/qa_classified.txt         — remaining files classified: RISK|BUCKET|PATH
#   /tmp/qa_deep_candidates.txt    — files selected for deep analysis: RISK|BUCKET|LINES|PATH
#   /tmp/qa_summary.txt            — human-readable summary
#
# Performance: uses ripgrep (rg) for bulk content scanning instead of per-file loops.
# Fallback to grep if rg not available.
#
# Exit code: 0 on success, 1 on error

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
MODE="main"
SCOPE=""
BASE_BRANCH="master"
EXTENSIONS="cs|java|ts|tsx|js|jsx|py|go|rb"
MAX_DEEP=150
MIN_DEEP=80
DEEP_RATIO="0.20"

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)        MODE="$2"; shift 2;;
    --scope)       SCOPE="$2"; shift 2;;
    --base-branch) BASE_BRANCH="$2"; shift 2;;
    *) echo "Unknown arg: $1" >&2; exit 1;;
  esac
done

# ── Tool detection ────────────────────────────────────────────────────────────
RG="rg"
if ! command -v rg &>/dev/null; then
  RG=""
  echo "WARN: ripgrep (rg) not found, using grep (slower)" >&2
fi

# ── Temp files ────────────────────────────────────────────────────────────────
RAW="/tmp/qa_raw_files.txt"
ALL="/tmp/qa_all_source.txt"
EX_GEN="/tmp/qa_excluded_generated.txt"
EX_DTO="/tmp/qa_excluded_dto.txt"
CLASSIFIED="/tmp/qa_classified.txt"
DEEP="/tmp/qa_deep_candidates.txt"
SUMMARY="/tmp/qa_summary.txt"

for f in "$RAW" "$ALL" "$EX_GEN" "$EX_DTO" "$CLASSIFIED" "$DEEP" "$SUMMARY"; do > "$f"; done

echo "qa-discover-files.sh starting (mode=$MODE)" >&2

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 1: Discover raw files
# ══════════════════════════════════════════════════════════════════════════════

if [[ "$MODE" == "feature" ]]; then
  git diff --name-status "${BASE_BRANCH}...HEAD" | \
    awk '$1 != "D" { print ($1 ~ /^R/ ? $3 : $2) }' | \
    grep -iE "\.(${EXTENSIONS})$" > "$RAW" || true
else
  find . -type f \
    -regextype posix-extended \
    -iregex ".*\.(${EXTENSIONS})" \
    -not -path "*/.vs/*" \
    -not -path "*/.git/*" \
    2>/dev/null | sort > "$RAW"
fi

RAW_COUNT=$(wc -l < "$RAW")
echo "Raw source files found: $RAW_COUNT" >> "$SUMMARY"

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 2: Directory exclusion (cheapest — path-only grep)
# ══════════════════════════════════════════════════════════════════════════════

grep -ivE '/(tests|test|__tests__|spec|__mocks__|fixtures|node_modules|vendor|dist|build|bin|obj|Generated|AutoGenerated|__generated__|Migrations|Connected Services)/|\.(Tests|Test)/' \
  "$RAW" > "${RAW}.phase2" || true

AFTER_DIR=$(wc -l < "${RAW}.phase2")
echo "After directory exclusion: $AFTER_DIR (removed $((RAW_COUNT - AFTER_DIR)))" >> "$SUMMARY"

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 3: Naming exclusion (cheap — filename-only grep)
# ══════════════════════════════════════════════════════════════════════════════

grep -ivE '\.test\.|\.spec\.|Tests\.cs$|Test\.java$|_test\.py$|_test\.go$|\.stories\.|\.d\.ts$|\.generated\.cs$|\.Generated\.cs$|\.designer\.cs$|\.Designer\.cs$|\.g\.cs$|\.g\.i\.cs$|\.tt\.cs$|Grpc\.cs$|\.pb\.cs$' \
  "${RAW}.phase2" > "${RAW}.phase3" || true

AFTER_NAME=$(wc -l < "${RAW}.phase3")
echo "After naming exclusion: $AFTER_NAME (removed $((AFTER_DIR - AFTER_NAME)))" >> "$SUMMARY"

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 4: Content-based generated code exclusion
#
# Strategy: Use rg (ripgrep) to bulk-search all files at once for generated
# markers, then subtract matched files. This is O(1) passes over disk instead
# of O(N) head+grep per file.
# ══════════════════════════════════════════════════════════════════════════════

echo "Phase 4: Scanning for generated-code markers (bulk)..." >&2

# Build a combined regex for all generated-code markers
GEN_PATTERN='(// <auto-generated|This code was generated by|auto-generated by xsd|Generated by:.*swagger|Generated by:.*openapi|GeneratedCodeAttribute|System\.CodeDom\.Compiler\.GeneratedCode|generated by Refitter|generated by NSwag|generated by AutoRest|generated by Kiota|xsd\.exe.*/c\b)'

# Collect files to scan into a temp list for --files-from
cp "${RAW}.phase3" /tmp/qa_phase4_input.txt

# Use rg to find files with generated markers in first 30 lines
# rg --files-from reads file list, -l outputs matching filenames only
if [[ -n "$RG" ]]; then
  # rg approach: search with context limited to first 30 lines via preprocessing
  # Since rg doesn't support "first N lines only", use a two-step:
  # Step 1: For each marker, grep file list
  > /tmp/qa_gen_matches.txt

  # Bulk extract first 15 lines of each file and tag with filename
  # Use awk to process the file list and output tagged headers
  while IFS= read -r filepath; do
    head -15 "$filepath" 2>/dev/null | grep -iE "$GEN_PATTERN" && echo "MATCH|$filepath" >> /tmp/qa_gen_matches.txt || true
  done < /tmp/qa_phase4_input.txt

  # Actually the above is still per-file. Let's use rg on the file list instead:
  # rg can search specific files listed and we limit to first 30 lines per file
  rg -il --max-count=1 \
    "$GEN_PATTERN" \
    $(cat /tmp/qa_phase4_input.txt | tr '\n' ' ') \
    2>/dev/null > /tmp/qa_gen_matches_rg.txt || true

  # Merge both match sources and deduplicate
  cat /tmp/qa_gen_matches.txt 2>/dev/null | grep "^MATCH|" | cut -d'|' -f2 >> /tmp/qa_gen_hits.txt || true
  cat /tmp/qa_gen_matches_rg.txt 2>/dev/null >> /tmp/qa_gen_hits.txt || true
  sort -u /tmp/qa_gen_hits.txt -o /tmp/qa_gen_hits.txt 2>/dev/null || true
else
  # grep fallback: search each file (slower)
  > /tmp/qa_gen_hits.txt
  while IFS= read -r filepath; do
    if head -15 "$filepath" 2>/dev/null | grep -qiE "$GEN_PATTERN"; then
      echo "$filepath" >> /tmp/qa_gen_hits.txt
    fi
  done < /tmp/qa_phase4_input.txt
fi

# Now verify hits are in first 15 lines (rg may match deeper lines)
# and record reason
> "$EX_GEN"
while IFS= read -r filepath; do
  header=$(head -15 "$filepath" 2>/dev/null || true)
  reason=""
  if echo "$header" | grep -qi '// <auto-generated'; then
    reason="auto-generated marker"
  elif echo "$header" | grep -qi 'This code was generated by'; then
    reason="tool-generated marker"
  elif echo "$header" | grep -qi 'auto-generated by xsd'; then
    reason="xsd-generated"
  elif echo "$header" | grep -qiE 'Generated by:.*(swagger|openapi)'; then
    reason="swagger/openapi-generated"
  elif echo "$header" | grep -qi 'GeneratedCodeAttribute\|System\.CodeDom\.Compiler\.GeneratedCode'; then
    reason="GeneratedCodeAttribute"
  elif echo "$header" | grep -qiE 'generated by (Refitter|NSwag|AutoRest|Kiota)'; then
    reason="api-client-generated"
  elif echo "$header" | grep -qi 'xsd\.exe.*/c'; then
    reason="xsd.exe instruction (generated)"
  fi
  [[ -n "$reason" ]] && echo "$reason|$filepath" >> "$EX_GEN"
done < /tmp/qa_gen_hits.txt 2>/dev/null

GENERATED_COUNT=$(wc -l < "$EX_GEN")

# Subtract generated files from the source list
if [[ "$GENERATED_COUNT" -gt 0 ]]; then
  cut -d'|' -f2 "$EX_GEN" | sort > /tmp/qa_gen_paths.txt
  sort "${RAW}.phase3" | comm -23 - /tmp/qa_gen_paths.txt > "$ALL"
else
  cp "${RAW}.phase3" "$ALL"
fi

AFTER_CONTENT=$(wc -l < "$ALL")
echo "After generated-code exclusion: $AFTER_CONTENT (removed $GENERATED_COUNT)" >> "$SUMMARY"

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 5: Scope narrowing (if --scope provided)
# ══════════════════════════════════════════════════════════════════════════════

if [[ -n "$SCOPE" ]]; then
  grep -iE "$SCOPE" "$ALL" > "${ALL}.scoped" || true
  mv "${ALL}.scoped" "$ALL"
  echo "After scope narrowing ($SCOPE): $(wc -l < "$ALL")" >> "$SUMMARY"
fi

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 6: Classify all remaining files (risk + bucket) — single awk pass
# ══════════════════════════════════════════════════════════════════════════════

echo "Phase 6: Classifying files..." >&2

awk '
{
  f = $0
  fl = tolower(f)
  bucket = "other"
  risk = "LOW"

  # ── HIGH risk ──
  if (fl ~ /login|auth|jwt|token|password|captcha|crypto|hash[^m]|mfa|otp|sso|security|shield|oauth|authorize/) {
    bucket = "security"; risk = "HIGH"
  }
  else if (fl ~ /payment|invoice|settlement|reconciliation|billing|price[^i]|currency|financial|advance[^d]/) {
    bucket = "financial"; risk = "HIGH"
  }
  else if (fl ~ /httpclient|restclient|grpcclient|serviceclient|externalservice|webservice|apiclient|apigateway|servicemanager|ticketmanager|serviceadapter/) {
    bucket = "external-integration"; risk = "HIGH"
  }

  # ── MEDIUM risk ──
  else if (fl ~ /datetime|timezone|calendar|schedule[^d]|cron|timer|expir|nodatime/) {
    bucket = "date-time"; risk = "MEDIUM"
  }
  else if (fl ~ /controller\.(cs|java|py|go|rb|ts|js)$/) {
    bucket = "public-api"; risk = "MEDIUM"
  }
  else if (fl ~ /middleware|handler\.(cs|java|py)$/) {
    bucket = "public-api"; risk = "MEDIUM"
  }
  else if (fl ~ /worker|backgroundservice|hostedservice|queue|consumer/) {
    bucket = "background-processing"; risk = "MEDIUM"
  }
  else if (fl ~ /service\.(cs|java|py)$/) {
    bucket = "service"; risk = "MEDIUM"
  }
  else if (fl ~ /repository|dbcontext|dataaccess|unitofwork/) {
    bucket = "data-access"; risk = "MEDIUM"
  }

  # ── LOW risk ──
  else if (fl ~ /\/dto\/|\/dtos\/|\/models\/|\/viewmodels\/|\/requests\/|\/responses\/|\/entity\/|\/entities\//) {
    bucket = "dto-model"; risk = "LOW"
  }
  else if (fl ~ /dto\.(cs|java|py)$|model\.(cs|java|py)$|request\.(cs|java|py)$|response\.(cs|java|py)$|reply\.(cs|java|py)$|viewmodel\.(cs|java|py)$/) {
    bucket = "dto-model"; risk = "LOW"
  }
  else if (fl ~ /\/messages\/|\/pmummessages\//) {
    bucket = "dto-model"; risk = "LOW"
  }
  else if (fl ~ /constants|enums|startup|program\.(cs|java|py)$|config|extension/) {
    bucket = "configuration"; risk = "LOW"
  }
  else if (fl ~ /infrastructure|helper|util[^s]|cache[^d]|logger|logging/) {
    bucket = "infrastructure"; risk = "LOW"
  }
  else if (f ~ /\/I[A-Z][a-zA-Z]*\.(cs|java|ts)$/) {
    bucket = "interface"; risk = "LOW"
  }

  print risk "|" bucket "|" f
}
' "$ALL" > "$CLASSIFIED"

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 7: DTO content verification (bulk — rg for method signatures)
#
# Instead of reading each DTO file, use rg to find DTO-classified files that
# contain non-trivial method bodies (public/private methods with >3 line bodies).
# Promote those to MEDIUM.
# ══════════════════════════════════════════════════════════════════════════════

echo "Phase 7: Verifying DTOs for hidden logic..." >&2

grep "|dto-model|" "$CLASSIFIED" | cut -d'|' -f3 > /tmp/qa_dto_paths.txt
DTO_TOTAL=$(wc -l < /tmp/qa_dto_paths.txt)
DTO_PROMOTED=0

# Heuristic: search for method-like signatures that aren't just get/set
# A file with "void|Task|async|static.*(" that isn't a property is likely to have logic
METHOD_PATTERN='\b(public|private|protected|internal)\b.+\b(void|Task|async|static|string|int|bool|decimal|List|Dictionary|IEnumerable)\b.+\('

if [[ -n "$RG" ]] && [[ -s /tmp/qa_dto_paths.txt ]]; then
  # rg: find DTO files containing method signatures
  rg -l "$METHOD_PATTERN" \
    $(cat /tmp/qa_dto_paths.txt | tr '\n' ' ') \
    2>/dev/null > /tmp/qa_dto_with_methods.txt || true
else
  grep -rlE "$METHOD_PATTERN" \
    $(cat /tmp/qa_dto_paths.txt | tr '\n' ' ') \
    2>/dev/null > /tmp/qa_dto_with_methods.txt || true
fi

# For files with method signatures, verify they have >3 line method bodies
while IFS= read -r filepath; do
  body_lines=$(awk '
    /\b(public|private|protected|internal)\b.*(void|Task|async|static|string|int|bool|decimal|List).*\(/ && !/\bget\b.*\bset\b/ {
      in_method=1; depth=0; lines=0; next
    }
    in_method { lines++ }
    in_method && /\{/ { depth++ }
    in_method && /\}/ { depth--; if(depth<=0) { if(lines>3) found++; in_method=0 } }
    END { print found+0 }
  ' "$filepath" 2>/dev/null)

  if [[ "$body_lines" -gt 0 ]]; then
    echo "PROMOTED|$filepath" >> "$EX_DTO"
    # Update classification in-place
    escaped=$(echo "$filepath" | sed 's/[&/\]/\\&/g')
    sed -i "s|LOW|dto-model|${escaped}|MEDIUM|service|${escaped}|" "$CLASSIFIED" 2>/dev/null || true
    ((DTO_PROMOTED++)) || true
  fi
done < /tmp/qa_dto_with_methods.txt 2>/dev/null

echo "DTO verification: $DTO_TOTAL checked, $DTO_PROMOTED promoted (had logic)" >> "$SUMMARY"

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 8: Select deep-analysis candidates + compute line counts
# ══════════════════════════════════════════════════════════════════════════════

echo "Phase 8: Selecting deep-analysis candidates..." >&2

TOTAL_FILES=$(wc -l < "$CLASSIFIED")

# Get line counts for non-DTO files (needed for selection)
grep -v "|dto-model|" "$CLASSIFIED" | while IFS='|' read -r risk bucket path; do
  lines=$(wc -l < "$path" 2>/dev/null || echo "0")
  echo "${risk}|${bucket}|${lines}|${path}"
done > /tmp/qa_with_lines.txt

# Selection rules:
# 1. All HIGH risk files
grep "^HIGH|" /tmp/qa_with_lines.txt >> "$DEEP" 2>/dev/null || true

# 2. Public-api files > 200 lines
awk -F'|' '$1 == "MEDIUM" && $2 == "public-api" && $3+0 > 200' /tmp/qa_with_lines.txt >> "$DEEP" 2>/dev/null || true

# 3. Service files > 300 lines
awk -F'|' '$1 == "MEDIUM" && $2 == "service" && $3+0 > 300' /tmp/qa_with_lines.txt >> "$DEEP" 2>/dev/null || true

# 4. All date-time and background-processing files
awk -F'|' '$2 == "date-time" || $2 == "background-processing"' /tmp/qa_with_lines.txt >> "$DEEP" 2>/dev/null || true

# 5. Data-access files > 200 lines
awk -F'|' '$1 == "MEDIUM" && $2 == "data-access" && $3+0 > 200' /tmp/qa_with_lines.txt >> "$DEEP" 2>/dev/null || true

# Deduplicate
sort -u "$DEEP" -o "$DEEP"
DEEP_COUNT=$(wc -l < "$DEEP")

# Fill to minimum if needed
if [[ "$TOTAL_FILES" -gt 120 ]]; then
  TARGET=$(awk "BEGIN { t=int($TOTAL_FILES * $DEEP_RATIO + 0.999); t=(t<$MIN_DEEP?$MIN_DEEP:t); t=(t>$MAX_DEEP?$MAX_DEEP:t); print t }")
  if [[ "$DEEP_COUNT" -lt "$TARGET" ]]; then
    NEED=$((TARGET - DEEP_COUNT))
    # Add largest MEDIUM files not already selected
    comm -23 <(sort /tmp/qa_with_lines.txt) <(sort "$DEEP") | \
      grep "^MEDIUM|" | \
      sort -t'|' -k3 -rn | \
      head -"$NEED" >> "$DEEP" 2>/dev/null || true
    sort -u "$DEEP" -o "$DEEP"
  fi
fi

DEEP_COUNT=$(wc -l < "$DEEP")

# ══════════════════════════════════════════════════════════════════════════════
# PHASE 9: Summary
# ══════════════════════════════════════════════════════════════════════════════

{
  echo ""
  echo "=== FINAL COUNTS ==="
  echo "Total source files (after all exclusions): $(wc -l < "$ALL")"
  echo "Generated code excluded: $GENERATED_COUNT"
  echo "DTO files verified: $DTO_TOTAL (promoted: $DTO_PROMOTED)"
  echo "Files selected for deep analysis: $DEEP_COUNT"
  echo ""
  echo "=== BY RISK ==="
  cut -d'|' -f1 "$CLASSIFIED" | sort | uniq -c | sort -rn
  echo ""
  echo "=== BY BUCKET ==="
  cut -d'|' -f2 "$CLASSIFIED" | sort | uniq -c | sort -rn
  echo ""
  echo "=== DEEP ANALYSIS BY BUCKET ==="
  cut -d'|' -f2 "$DEEP" | sort | uniq -c | sort -rn
  echo ""
  echo "=== GENERATED CODE EXCLUDED ==="
  cat "$EX_GEN"
} >> "$SUMMARY"

# Print summary to stdout
cat "$SUMMARY"

# Cleanup temp intermediates
rm -f "${RAW}" "${RAW}.phase2" "${RAW}.phase3" \
  /tmp/qa_phase4_input.txt /tmp/qa_gen_matches.txt /tmp/qa_gen_matches_rg.txt \
  /tmp/qa_gen_hits.txt /tmp/qa_gen_paths.txt /tmp/qa_dto_paths.txt \
  /tmp/qa_dto_with_methods.txt /tmp/qa_with_lines.txt

echo "" >&2
echo "Done. Output files: /tmp/qa_all_source.txt, /tmp/qa_classified.txt, /tmp/qa_deep_candidates.txt" >&2
