using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.CompilerServices;
using FluentAssertions;
using Microsoft.EntityFrameworkCore.Design;
using NetArchTest.Rules;
using Xunit;

namespace Kartova.ArchitectureTests;

/// <summary>
/// DTOs and other pure data carriers do not have testable behavior — equality, hash code,
/// and getters are auto-generated by the compiler or trivially correct. Forcing them
/// into the coverage denominator dilutes the score and rewards busywork "DTO tests."
/// All such types must carry <see cref="ExcludeFromCodeCoverageAttribute"/>.
///
/// Convention: any type living in a *.Contracts assembly, or any type whose name ends in
/// Dto / Request / Response, is treated as a pure data carrier.
/// </summary>
public class ContractsCoverageRules
{
    // Compiler-emitted and tooling-injected synthetic type names: <Module>, <PrivateImplementationDetails>,
    // closure types like <>c__DisplayClass*, anonymous-type backing classes <>f__AnonymousType*.
    // Coverlet's instrumentation tracker types live in the Coverlet.* namespace and are also filtered
    // out by namespace; this regex covers the "<…>" synthetic-name shape regardless of namespace.
    private const string SyntheticTypeNamePattern = @"^<.*>.*$";


    [Fact]
    public void All_types_in_Contracts_assemblies_have_ExcludeFromCodeCoverage()
    {
        var contractsAssemblies = AssemblyRegistry.AllContracts().ToArray();
        contractsAssemblies.Should().NotBeEmpty();

        var result = Types.InAssemblies(contractsAssemblies)
            .That().AreClasses()
            .And().DoNotHaveCustomAttribute(typeof(CompilerGeneratedAttribute))
            .And().DoNotResideInNamespaceStartingWith("Coverlet.")
            .And().DoNotHaveNameMatching(SyntheticTypeNamePattern)
            .Should().HaveCustomAttribute(typeof(ExcludeFromCodeCoverageAttribute))
            .GetResult();

        result.IsSuccessful.Should().BeTrue(
            because: BuildFailureMessage(result, "Every type in a *.Contracts assembly is a pure data carrier and must be decorated with [ExcludeFromCodeCoverage]"));
    }

    [Fact]
    public void DTO_like_types_have_ExcludeFromCodeCoverage()
    {
        var production = AssemblyRegistry.AllProduction().ToArray();

        var result = Types.InAssemblies(production)
            .That()
            .DoNotHaveCustomAttribute(typeof(CompilerGeneratedAttribute))
            .And().DoNotResideInNamespaceStartingWith("Coverlet.")
            .And().DoNotHaveNameMatching(SyntheticTypeNamePattern)
            .And().HaveNameEndingWith("Dto")
            .Or().HaveNameEndingWith("Request")
            .Or().HaveNameEndingWith("Response")
            .Should().HaveCustomAttribute(typeof(ExcludeFromCodeCoverageAttribute))
            .GetResult();

        result.IsSuccessful.Should().BeTrue(
            because: BuildFailureMessage(result, "Types named *Dto / *Request / *Response are pure data carriers and must be decorated with [ExcludeFromCodeCoverage]"));
    }

    [Fact]
    public void DesignTime_DbContext_factories_have_ExcludeFromCodeCoverage()
    {
        var production = AssemblyRegistry.AllProduction().ToArray();
        var factoryInterface = typeof(IDesignTimeDbContextFactory<>);

        var factories = production
            .SelectMany(a => a.GetTypes())
            .Where(t => !t.IsAbstract && t.IsClass &&
                t.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == factoryInterface))
            .ToArray();

        var missing = factories
            .Where(t => t.GetCustomAttributes(typeof(ExcludeFromCodeCoverageAttribute), inherit: false).Length == 0)
            .Select(t => t.FullName)
            .ToArray();

        missing.Should().BeEmpty(
            because: "Design-time IDesignTimeDbContextFactory<> implementations are run only by `dotnet ef`. " +
                     "They must carry [ExcludeFromCodeCoverage] per CLAUDE.md §Coverage exclusion. " +
                     "Offending types: " + string.Join(", ", missing));
    }

    private static string BuildFailureMessage(TestResult result, string lead)
    {
        if (result.IsSuccessful) return lead;
        var offenders = result.FailingTypeNames is null
            ? "(no failing types reported)"
            : string.Join(", ", result.FailingTypeNames);
        return $"{lead}. Offending types: {offenders}";
    }
}
