// <auto-generated />
using System;
using System.Collections.Generic;
using Kartova.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kartova.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260705111604_PurgePartOfRelationships")]
    partial class PurgePartOfRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kartova.Catalog.Domain.Api", b =>
                {
                    b.Property<Guid>("_id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("SpecUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("spec_url");

                    b.Property<short>("Style")
                        .HasColumnType("smallint")
                        .HasColumnName("style");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("idx_catalog_apis_team");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_apis_tenant_id");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasDatabaseName("ix_catalog_apis_tenant_id_display_name");

                    b.ToTable("catalog_apis", (string)null);
                });

            modelBuilder.Entity("Kartova.Catalog.Domain.Application", b =>
                {
                    b.Property<Guid>("_id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<short>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("lifecycle");

                    b.Property<Guid?>("SuccessorApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("successor_application_id");

                    b.Property<DateTimeOffset?>("SunsetDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sunset_date");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("_id");

                    b.HasIndex("SuccessorApplicationId")
                        .HasDatabaseName("ix_catalog_applications_successor_application_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("idx_catalog_applications_team");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_applications_tenant_id");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasDatabaseName("ix_catalog_applications_tenant_id_display_name");

                    b.ToTable("catalog_applications", (string)null);
                });

            modelBuilder.Entity("Kartova.Catalog.Domain.Relationship", b =>
                {
                    b.Property<Guid>("_id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Source", "Kartova.Catalog.Domain.Relationship.Source#EntityRef", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("source_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("source_kind");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Target", "Kartova.Catalog.Domain.Relationship.Target#EntityRef", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("target_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("target_kind");
                        });

                    b.HasKey("_id");

                    b.ToTable("relationships", (string)null);
                });

            modelBuilder.Entity("Kartova.Catalog.Domain.Service", b =>
                {
                    b.Property<Guid>("_id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<short>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("health");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("idx_catalog_services_team");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_services_tenant_id");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasDatabaseName("ix_catalog_services_tenant_id_display_name");

                    b.ToTable("catalog_services", (string)null);
                });

            modelBuilder.Entity("Kartova.Catalog.Infrastructure.KartovaMetadata", b =>
                {
                    b.Property<string>("ModuleName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_name");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("ModuleName");

                    b.ToTable("__kartova_metadata", (string)null);
                });

            modelBuilder.Entity("Kartova.Catalog.Domain.Application", b =>
                {
                    b.HasOne("Kartova.Catalog.Domain.Application", null)
                        .WithMany()
                        .HasForeignKey("SuccessorApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kartova.Catalog.Domain.Service", b =>
                {
                    b.OwnsMany("Kartova.Catalog.Domain.ServiceEndpoint", "Endpoints", b1 =>
                        {
                            b1.Property<Guid>("Service_id");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<short>("Protocol")
                                .HasJsonPropertyName("protocol");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasJsonPropertyName("url");

                            b1.HasKey("Service_id", "__synthesizedOrdinal");

                            b1.ToTable("catalog_services");

                            b1
                                .ToJson("endpoints")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("Service_id");
                        });

                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
